FROM openjdk:17
VOLUME /tmp
EXPOSE 8081
ARG JAR_FILE=target/projectEmailService-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} projectEmailService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/projectEmailService-0.0.1-SNAPSHOT.jar"]